// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ssip_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SSIP;

public interface _DAQOperations
{
    int bulkInAnalog(byte[] data, Ice.Current __current);

    int bulkInDigital(byte[] data, Ice.Current __current);

    int bulkInAccumulator(byte[] data, Ice.Current __current);
}
