// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ssip_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SSIP;

public interface DACPrx extends Ice.ObjectPrx
{
    public int sendAlarm(byte[] msg);

    public int sendAlarm(byte[] msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendAlarm(byte[] msg);

    public Ice.AsyncResult begin_sendAlarm(byte[] msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendAlarm(byte[] msg, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendAlarm(byte[] msg, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendAlarm(byte[] msg, Callback_DAC_sendAlarm __cb);

    public Ice.AsyncResult begin_sendAlarm(byte[] msg, java.util.Map<String, String> __ctx, Callback_DAC_sendAlarm __cb);

    public int end_sendAlarm(Ice.AsyncResult __result);

    public int sendAlarmList(byte[] msg);

    public int sendAlarmList(byte[] msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendAlarmList(byte[] msg);

    public Ice.AsyncResult begin_sendAlarmList(byte[] msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendAlarmList(byte[] msg, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendAlarmList(byte[] msg, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendAlarmList(byte[] msg, Callback_DAC_sendAlarmList __cb);

    public Ice.AsyncResult begin_sendAlarmList(byte[] msg, java.util.Map<String, String> __ctx, Callback_DAC_sendAlarmList __cb);

    public int end_sendAlarmList(Ice.AsyncResult __result);
}
