// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ssip_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SSIP;

public final class DACPrxHelper extends Ice.ObjectPrxHelperBase implements DACPrx
{
    private static final String __sendAlarm_name = "sendAlarm";

    public int sendAlarm(byte[] msg)
    {
        return sendAlarm(msg, null, false);
    }

    public int sendAlarm(byte[] msg, java.util.Map<String, String> __ctx)
    {
        return sendAlarm(msg, __ctx, true);
    }

    private int sendAlarm(byte[] msg, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "sendAlarm", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("sendAlarm");
                    __delBase = __getDelegate(false);
                    _DACDel __del = (_DACDel)__delBase;
                    return __del.sendAlarm(msg, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_sendAlarm(byte[] msg)
    {
        return begin_sendAlarm(msg, null, false, null);
    }

    public Ice.AsyncResult begin_sendAlarm(byte[] msg, java.util.Map<String, String> __ctx)
    {
        return begin_sendAlarm(msg, __ctx, true, null);
    }

    public Ice.AsyncResult begin_sendAlarm(byte[] msg, Ice.Callback __cb)
    {
        return begin_sendAlarm(msg, null, false, __cb);
    }

    public Ice.AsyncResult begin_sendAlarm(byte[] msg, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_sendAlarm(msg, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_sendAlarm(byte[] msg, Callback_DAC_sendAlarm __cb)
    {
        return begin_sendAlarm(msg, null, false, __cb);
    }

    public Ice.AsyncResult begin_sendAlarm(byte[] msg, java.util.Map<String, String> __ctx, Callback_DAC_sendAlarm __cb)
    {
        return begin_sendAlarm(msg, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_sendAlarm(byte[] msg, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__sendAlarm_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __sendAlarm_name, __cb);
        try
        {
            __result.__prepare(__sendAlarm_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            ByteSeqHelper.write(__os, msg);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public int end_sendAlarm(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __sendAlarm_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            int __ret;
            __ret = __is.readInt();
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __sendAlarmList_name = "sendAlarmList";

    public int sendAlarmList(byte[] msg)
    {
        return sendAlarmList(msg, null, false);
    }

    public int sendAlarmList(byte[] msg, java.util.Map<String, String> __ctx)
    {
        return sendAlarmList(msg, __ctx, true);
    }

    private int sendAlarmList(byte[] msg, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "sendAlarmList", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("sendAlarmList");
                    __delBase = __getDelegate(false);
                    _DACDel __del = (_DACDel)__delBase;
                    return __del.sendAlarmList(msg, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_sendAlarmList(byte[] msg)
    {
        return begin_sendAlarmList(msg, null, false, null);
    }

    public Ice.AsyncResult begin_sendAlarmList(byte[] msg, java.util.Map<String, String> __ctx)
    {
        return begin_sendAlarmList(msg, __ctx, true, null);
    }

    public Ice.AsyncResult begin_sendAlarmList(byte[] msg, Ice.Callback __cb)
    {
        return begin_sendAlarmList(msg, null, false, __cb);
    }

    public Ice.AsyncResult begin_sendAlarmList(byte[] msg, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_sendAlarmList(msg, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_sendAlarmList(byte[] msg, Callback_DAC_sendAlarmList __cb)
    {
        return begin_sendAlarmList(msg, null, false, __cb);
    }

    public Ice.AsyncResult begin_sendAlarmList(byte[] msg, java.util.Map<String, String> __ctx, Callback_DAC_sendAlarmList __cb)
    {
        return begin_sendAlarmList(msg, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_sendAlarmList(byte[] msg, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__sendAlarmList_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __sendAlarmList_name, __cb);
        try
        {
            __result.__prepare(__sendAlarmList_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            ByteSeqHelper.write(__os, msg);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public int end_sendAlarmList(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __sendAlarmList_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            int __ret;
            __ret = __is.readInt();
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public static DACPrx checkedCast(Ice.ObjectPrx __obj)
    {
        DACPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DACPrx)
            {
                __d = (DACPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    DACPrxHelper __h = new DACPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DACPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        DACPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DACPrx)
            {
                __d = (DACPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    DACPrxHelper __h = new DACPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DACPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DACPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    DACPrxHelper __h = new DACPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DACPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        DACPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    DACPrxHelper __h = new DACPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DACPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        DACPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DACPrx)
            {
                __d = (DACPrx)__obj;
            }
            else
            {
                DACPrxHelper __h = new DACPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static DACPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DACPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            DACPrxHelper __h = new DACPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::SSIP::DAC"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _DACDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _DACDelD();
    }

    public static void __write(IceInternal.BasicStream __os, DACPrx v)
    {
        __os.writeProxy(v);
    }

    public static DACPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            DACPrxHelper result = new DACPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
