// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ssip_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SSIP;

public final class DAQPrxHelper extends Ice.ObjectPrxHelperBase implements DAQPrx
{
    private static final String __bulkInAccumulator_name = "bulkInAccumulator";

    public int bulkInAccumulator(byte[] data)
    {
        return bulkInAccumulator(data, null, false);
    }

    public int bulkInAccumulator(byte[] data, java.util.Map<String, String> __ctx)
    {
        return bulkInAccumulator(data, __ctx, true);
    }

    private int bulkInAccumulator(byte[] data, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "bulkInAccumulator", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("bulkInAccumulator");
                    __delBase = __getDelegate(false);
                    _DAQDel __del = (_DAQDel)__delBase;
                    return __del.bulkInAccumulator(data, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_bulkInAccumulator(byte[] data)
    {
        return begin_bulkInAccumulator(data, null, false, null);
    }

    public Ice.AsyncResult begin_bulkInAccumulator(byte[] data, java.util.Map<String, String> __ctx)
    {
        return begin_bulkInAccumulator(data, __ctx, true, null);
    }

    public Ice.AsyncResult begin_bulkInAccumulator(byte[] data, Ice.Callback __cb)
    {
        return begin_bulkInAccumulator(data, null, false, __cb);
    }

    public Ice.AsyncResult begin_bulkInAccumulator(byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_bulkInAccumulator(data, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_bulkInAccumulator(byte[] data, Callback_DAQ_bulkInAccumulator __cb)
    {
        return begin_bulkInAccumulator(data, null, false, __cb);
    }

    public Ice.AsyncResult begin_bulkInAccumulator(byte[] data, java.util.Map<String, String> __ctx, Callback_DAQ_bulkInAccumulator __cb)
    {
        return begin_bulkInAccumulator(data, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_bulkInAccumulator(byte[] data, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__bulkInAccumulator_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __bulkInAccumulator_name, __cb);
        try
        {
            __result.__prepare(__bulkInAccumulator_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            ByteSeqHelper.write(__os, data);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public int end_bulkInAccumulator(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __bulkInAccumulator_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            int __ret;
            __ret = __is.readInt();
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __bulkInAnalog_name = "bulkInAnalog";

    public int bulkInAnalog(byte[] data)
    {
        return bulkInAnalog(data, null, false);
    }

    public int bulkInAnalog(byte[] data, java.util.Map<String, String> __ctx)
    {
        return bulkInAnalog(data, __ctx, true);
    }

    private int bulkInAnalog(byte[] data, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "bulkInAnalog", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("bulkInAnalog");
                    __delBase = __getDelegate(false);
                    _DAQDel __del = (_DAQDel)__delBase;
                    return __del.bulkInAnalog(data, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_bulkInAnalog(byte[] data)
    {
        return begin_bulkInAnalog(data, null, false, null);
    }

    public Ice.AsyncResult begin_bulkInAnalog(byte[] data, java.util.Map<String, String> __ctx)
    {
        return begin_bulkInAnalog(data, __ctx, true, null);
    }

    public Ice.AsyncResult begin_bulkInAnalog(byte[] data, Ice.Callback __cb)
    {
        return begin_bulkInAnalog(data, null, false, __cb);
    }

    public Ice.AsyncResult begin_bulkInAnalog(byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_bulkInAnalog(data, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_bulkInAnalog(byte[] data, Callback_DAQ_bulkInAnalog __cb)
    {
        return begin_bulkInAnalog(data, null, false, __cb);
    }

    public Ice.AsyncResult begin_bulkInAnalog(byte[] data, java.util.Map<String, String> __ctx, Callback_DAQ_bulkInAnalog __cb)
    {
        return begin_bulkInAnalog(data, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_bulkInAnalog(byte[] data, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__bulkInAnalog_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __bulkInAnalog_name, __cb);
        try
        {
            __result.__prepare(__bulkInAnalog_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            ByteSeqHelper.write(__os, data);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public int end_bulkInAnalog(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __bulkInAnalog_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            int __ret;
            __ret = __is.readInt();
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __bulkInDigital_name = "bulkInDigital";

    public int bulkInDigital(byte[] data)
    {
        return bulkInDigital(data, null, false);
    }

    public int bulkInDigital(byte[] data, java.util.Map<String, String> __ctx)
    {
        return bulkInDigital(data, __ctx, true);
    }

    private int bulkInDigital(byte[] data, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "bulkInDigital", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("bulkInDigital");
                    __delBase = __getDelegate(false);
                    _DAQDel __del = (_DAQDel)__delBase;
                    return __del.bulkInDigital(data, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_bulkInDigital(byte[] data)
    {
        return begin_bulkInDigital(data, null, false, null);
    }

    public Ice.AsyncResult begin_bulkInDigital(byte[] data, java.util.Map<String, String> __ctx)
    {
        return begin_bulkInDigital(data, __ctx, true, null);
    }

    public Ice.AsyncResult begin_bulkInDigital(byte[] data, Ice.Callback __cb)
    {
        return begin_bulkInDigital(data, null, false, __cb);
    }

    public Ice.AsyncResult begin_bulkInDigital(byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_bulkInDigital(data, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_bulkInDigital(byte[] data, Callback_DAQ_bulkInDigital __cb)
    {
        return begin_bulkInDigital(data, null, false, __cb);
    }

    public Ice.AsyncResult begin_bulkInDigital(byte[] data, java.util.Map<String, String> __ctx, Callback_DAQ_bulkInDigital __cb)
    {
        return begin_bulkInDigital(data, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_bulkInDigital(byte[] data, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__bulkInDigital_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __bulkInDigital_name, __cb);
        try
        {
            __result.__prepare(__bulkInDigital_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            ByteSeqHelper.write(__os, data);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public int end_bulkInDigital(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __bulkInDigital_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            int __ret;
            __ret = __is.readInt();
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public static DAQPrx checkedCast(Ice.ObjectPrx __obj)
    {
        DAQPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DAQPrx)
            {
                __d = (DAQPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    DAQPrxHelper __h = new DAQPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DAQPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        DAQPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DAQPrx)
            {
                __d = (DAQPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    DAQPrxHelper __h = new DAQPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DAQPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DAQPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    DAQPrxHelper __h = new DAQPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DAQPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        DAQPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    DAQPrxHelper __h = new DAQPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DAQPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        DAQPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DAQPrx)
            {
                __d = (DAQPrx)__obj;
            }
            else
            {
                DAQPrxHelper __h = new DAQPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static DAQPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DAQPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            DAQPrxHelper __h = new DAQPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::SSIP::DAQ"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _DAQDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _DAQDelD();
    }

    public static void __write(IceInternal.BasicStream __os, DAQPrx v)
    {
        __os.writeProxy(v);
    }

    public static DAQPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            DAQPrxHelper result = new DAQPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
