// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ssip_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SSIP.NEWS;

public final class dms_publisherPrxHolder
{
    public
    dms_publisherPrxHolder()
    {
    }

    public
    dms_publisherPrxHolder(dms_publisherPrx value)
    {
        this.value = value;
    }

    public dms_publisherPrx value;
}
