// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ssip_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SSIP.NEWS;

public final class dms_observerPrxHelper extends Ice.ObjectPrxHelperBase implements dms_observerPrx
{
    private static final String __sendBytes_name = "sendBytes";

    public void sendBytes(byte[] data)
    {
        sendBytes(data, null, false);
    }

    public void sendBytes(byte[] data, java.util.Map<String, String> __ctx)
    {
        sendBytes(data, __ctx, true);
    }

    private void sendBytes(byte[] data, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "sendBytes", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _dms_observerDel __del = (_dms_observerDel)__delBase;
                    __del.sendBytes(data, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_sendBytes(byte[] data)
    {
        return begin_sendBytes(data, null, false, null);
    }

    public Ice.AsyncResult begin_sendBytes(byte[] data, java.util.Map<String, String> __ctx)
    {
        return begin_sendBytes(data, __ctx, true, null);
    }

    public Ice.AsyncResult begin_sendBytes(byte[] data, Ice.Callback __cb)
    {
        return begin_sendBytes(data, null, false, __cb);
    }

    public Ice.AsyncResult begin_sendBytes(byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_sendBytes(data, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_sendBytes(byte[] data, Callback_dms_observer_sendBytes __cb)
    {
        return begin_sendBytes(data, null, false, __cb);
    }

    public Ice.AsyncResult begin_sendBytes(byte[] data, java.util.Map<String, String> __ctx, Callback_dms_observer_sendBytes __cb)
    {
        return begin_sendBytes(data, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_sendBytes(byte[] data, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __sendBytes_name, __cb);
        try
        {
            __result.__prepare(__sendBytes_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            SSIP.ByteSeqHelper.write(__os, data);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_sendBytes(Ice.AsyncResult __result)
    {
        __end(__result, __sendBytes_name);
    }

    public static dms_observerPrx checkedCast(Ice.ObjectPrx __obj)
    {
        dms_observerPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof dms_observerPrx)
            {
                __d = (dms_observerPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    dms_observerPrxHelper __h = new dms_observerPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static dms_observerPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        dms_observerPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof dms_observerPrx)
            {
                __d = (dms_observerPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    dms_observerPrxHelper __h = new dms_observerPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static dms_observerPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        dms_observerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    dms_observerPrxHelper __h = new dms_observerPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static dms_observerPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        dms_observerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    dms_observerPrxHelper __h = new dms_observerPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static dms_observerPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        dms_observerPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof dms_observerPrx)
            {
                __d = (dms_observerPrx)__obj;
            }
            else
            {
                dms_observerPrxHelper __h = new dms_observerPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static dms_observerPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        dms_observerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            dms_observerPrxHelper __h = new dms_observerPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::SSIP::NEWS::dms_observer"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _dms_observerDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _dms_observerDelD();
    }

    public static void __write(IceInternal.BasicStream __os, dms_observerPrx v)
    {
        __os.writeProxy(v);
    }

    public static dms_observerPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            dms_observerPrxHelper result = new dms_observerPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
