server:
  port: 7002

spring:
  application:
    name: casco_devdata_ms

#  redis:
#     host: 127.0.0.1
#     password: test
#     port: 6379
#     timeout: 1000s
#     jedis:
#       pool:
#         max-idle: 500
#         min-idle: 50
#         max-wait: -1
#         max-active: -1
  redis:
    host: 10.153.102.2
    password: casco123
    port: 6379
    timeout: 1000s
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-wait: -1
        max-active: -1

  datasource:
    name: casco
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/casco_zhgs?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8
#    username: root
#    password: root
    url: jdbc:mysql://${MYSQL_HOST:10.153.102.3}:${MYSQL_PORT:3306}/casco_zhgs?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8
    username: root
    password: Casco@123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis-plus:
  #  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)