

DROP TABLE IF EXISTS SYS_ALARM_TABLE;
CREATE TABLE SYS_ALARM_TABLE (
LINE_NAME varchar(64) NOT NULL,
ARM_UUID varchar(64) NOT NULL,
ARM_EQU_TYPE varchar(64)  DEFAULT NULL,
ARM_EQU_NAME varchar(64)  DEFAULT NULL,
ARM_CONTENT varchar(256)  DEFAULT NULL,
ARM_EQU_CODE varchar(32)  DEFAULT NULL,
ARM_ADD_EQU varchar(128)  DEFAULT NULL,
ARM_SOURCE varchar(16)  DEFAULT NULL,
ARM_DBM varchar(4)  DEFAULT NULL,
ARM_HAPPEN_TIME datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
ARM_RESTORE_TIME datetime DEFAULT NULL,
ARM_FAULT_BEGIN float DEFAULT NULL,
ARM_FAULT_BEG_MS float DEFAULT NULL,
ARM_FAULT_END float DEFAULT NULL,
ARM_FAULT_END_MS float DEFAULT NULL,
ARM_CODE float DEFAULT NULL,
ARM_EQU_TYPECODE float DEFAULT NULL,
ARM_LOGIC_TYPE1 float DEFAULT NULL,
ARM_LOGIC_TYPE2 float DEFAULT NULL,
ARM_LOGIC_TYPE3 float DEFAULT NULL,
ARM_LEVEL float DEFAULT NULL,
ARM_IS_MAINTAIN float DEFAULT NULL,
ARM_SAVE_NO float DEFAULT NULL,
ARM_ADD_JSON varchar(256) DEFAULT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT=' ';