// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ssip_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SSIP;

public interface _dms_factoryOperationsNC
{
    boolean isMainServer(String server);

    DACPrx getDac();

    DAQPrx getDaq();

    COMCTRLPrx getComctrl();

    SSIP.NEWS.dms_observerPrx getObserver();

    SSIP.NEWS.dms_publisherPrx getPubliser();
}
