// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ssip_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SSIP;

public interface _dms_factoryOperations
{
    boolean isMainServer(String server, Ice.Current __current);

    DACPrx getDac(Ice.Current __current);

    DAQPrx getDaq(Ice.Current __current);

    COMCTRLPrx getComctrl(Ice.Current __current);

    SSIP.NEWS.dms_observerPrx getObserver(Ice.Current __current);

    SSIP.NEWS.dms_publisherPrx getPubliser(Ice.Current __current);
}
