// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ssip_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SSIP;

public final class dms_factoryPrxHolder
{
    public
    dms_factoryPrxHolder()
    {
    }

    public
    dms_factoryPrxHolder(dms_factoryPrx value)
    {
        this.value = value;
    }

    public dms_factoryPrx value;
}
