// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ssip_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SSIP.NEWS;

public interface dms_observerPrx extends Ice.ObjectPrx
{
    public void sendBytes(byte[] data);

    public void sendBytes(byte[] data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendBytes(byte[] data);

    public Ice.AsyncResult begin_sendBytes(byte[] data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendBytes(byte[] data, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendBytes(byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendBytes(byte[] data, Callback_dms_observer_sendBytes __cb);

    public Ice.AsyncResult begin_sendBytes(byte[] data, java.util.Map<String, String> __ctx, Callback_dms_observer_sendBytes __cb);

    public void end_sendBytes(Ice.AsyncResult __result);
}
