// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ssip_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SSIP.NEWS;

public final class dms_publisherPrxHelper extends Ice.ObjectPrxHelperBase implements dms_publisherPrx
{
    private static final String __subscribe_name = "subscribe";

    public boolean subscribe(dms_observerPrx observer, MetaTopic topic, MetaPara[] params)
    {
        return subscribe(observer, topic, params, null, false);
    }

    public boolean subscribe(dms_observerPrx observer, MetaTopic topic, MetaPara[] params, java.util.Map<String, String> __ctx)
    {
        return subscribe(observer, topic, params, __ctx, true);
    }

    private boolean subscribe(dms_observerPrx observer, MetaTopic topic, MetaPara[] params, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "subscribe", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("subscribe");
                    __delBase = __getDelegate(false);
                    _dms_publisherDel __del = (_dms_publisherDel)__delBase;
                    return __del.subscribe(observer, topic, params, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_subscribe(dms_observerPrx observer, MetaTopic topic, MetaPara[] params)
    {
        return begin_subscribe(observer, topic, params, null, false, null);
    }

    public Ice.AsyncResult begin_subscribe(dms_observerPrx observer, MetaTopic topic, MetaPara[] params, java.util.Map<String, String> __ctx)
    {
        return begin_subscribe(observer, topic, params, __ctx, true, null);
    }

    public Ice.AsyncResult begin_subscribe(dms_observerPrx observer, MetaTopic topic, MetaPara[] params, Ice.Callback __cb)
    {
        return begin_subscribe(observer, topic, params, null, false, __cb);
    }

    public Ice.AsyncResult begin_subscribe(dms_observerPrx observer, MetaTopic topic, MetaPara[] params, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_subscribe(observer, topic, params, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_subscribe(dms_observerPrx observer, MetaTopic topic, MetaPara[] params, Callback_dms_publisher_subscribe __cb)
    {
        return begin_subscribe(observer, topic, params, null, false, __cb);
    }

    public Ice.AsyncResult begin_subscribe(dms_observerPrx observer, MetaTopic topic, MetaPara[] params, java.util.Map<String, String> __ctx, Callback_dms_publisher_subscribe __cb)
    {
        return begin_subscribe(observer, topic, params, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_subscribe(dms_observerPrx observer, MetaTopic topic, MetaPara[] params, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__subscribe_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __subscribe_name, __cb);
        try
        {
            __result.__prepare(__subscribe_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            dms_observerPrxHelper.__write(__os, observer);
            topic.__write(__os);
            ParaSeqHelper.write(__os, params);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public boolean end_subscribe(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __subscribe_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            boolean __ret;
            __ret = __is.readBool();
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __unsubscribe_name = "unsubscribe";

    public boolean unsubscribe(dms_observerPrx observer, int subscribeno)
    {
        return unsubscribe(observer, subscribeno, null, false);
    }

    public boolean unsubscribe(dms_observerPrx observer, int subscribeno, java.util.Map<String, String> __ctx)
    {
        return unsubscribe(observer, subscribeno, __ctx, true);
    }

    private boolean unsubscribe(dms_observerPrx observer, int subscribeno, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "unsubscribe", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("unsubscribe");
                    __delBase = __getDelegate(false);
                    _dms_publisherDel __del = (_dms_publisherDel)__delBase;
                    return __del.unsubscribe(observer, subscribeno, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_unsubscribe(dms_observerPrx observer, int subscribeno)
    {
        return begin_unsubscribe(observer, subscribeno, null, false, null);
    }

    public Ice.AsyncResult begin_unsubscribe(dms_observerPrx observer, int subscribeno, java.util.Map<String, String> __ctx)
    {
        return begin_unsubscribe(observer, subscribeno, __ctx, true, null);
    }

    public Ice.AsyncResult begin_unsubscribe(dms_observerPrx observer, int subscribeno, Ice.Callback __cb)
    {
        return begin_unsubscribe(observer, subscribeno, null, false, __cb);
    }

    public Ice.AsyncResult begin_unsubscribe(dms_observerPrx observer, int subscribeno, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_unsubscribe(observer, subscribeno, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_unsubscribe(dms_observerPrx observer, int subscribeno, Callback_dms_publisher_unsubscribe __cb)
    {
        return begin_unsubscribe(observer, subscribeno, null, false, __cb);
    }

    public Ice.AsyncResult begin_unsubscribe(dms_observerPrx observer, int subscribeno, java.util.Map<String, String> __ctx, Callback_dms_publisher_unsubscribe __cb)
    {
        return begin_unsubscribe(observer, subscribeno, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_unsubscribe(dms_observerPrx observer, int subscribeno, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__unsubscribe_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __unsubscribe_name, __cb);
        try
        {
            __result.__prepare(__unsubscribe_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            dms_observerPrxHelper.__write(__os, observer);
            __os.writeInt(subscribeno);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public boolean end_unsubscribe(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __unsubscribe_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            boolean __ret;
            __ret = __is.readBool();
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public static dms_publisherPrx checkedCast(Ice.ObjectPrx __obj)
    {
        dms_publisherPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof dms_publisherPrx)
            {
                __d = (dms_publisherPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    dms_publisherPrxHelper __h = new dms_publisherPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static dms_publisherPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        dms_publisherPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof dms_publisherPrx)
            {
                __d = (dms_publisherPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    dms_publisherPrxHelper __h = new dms_publisherPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static dms_publisherPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        dms_publisherPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    dms_publisherPrxHelper __h = new dms_publisherPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static dms_publisherPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        dms_publisherPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    dms_publisherPrxHelper __h = new dms_publisherPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static dms_publisherPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        dms_publisherPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof dms_publisherPrx)
            {
                __d = (dms_publisherPrx)__obj;
            }
            else
            {
                dms_publisherPrxHelper __h = new dms_publisherPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static dms_publisherPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        dms_publisherPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            dms_publisherPrxHelper __h = new dms_publisherPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::SSIP::NEWS::dms_publisher"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _dms_publisherDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _dms_publisherDelD();
    }

    public static void __write(IceInternal.BasicStream __os, dms_publisherPrx v)
    {
        __os.writeProxy(v);
    }

    public static dms_publisherPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            dms_publisherPrxHelper result = new dms_publisherPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
